hosts: 
  host1-DC1:
    switches: [leaf1-DC1, leaf2-DC1]
    ports: [e6, e7, e6, e7]
    mode: access
    vlan: 101
  host2-DC1:
    switches: [leaf3-DC1, leaf4-DC1]
    ports: [e6, e7, e6, e7]
    mode: access
    vlan: 101