---
- name: Download ATD-INFRA configlet (using RestAPI)
  hosts: CloudVision
  vars:
    authURL: "https://192.168.0.5/cvpservice/login/authenticate.do"
    configlet_url: "https://192.168.0.5/cvpservice/configlet/getConfigletByName.do?name="
    configlet_name: "ATD-INFRA"
    CVP_password: "aristaifvc"

  tasks:
  - name: Authenticate and grab token
    uri:
      method: POST
      validate_certs: no
      return_content: yes
      url: "{{ authURL }}"
      body_format: json
      body:
        userId: arista
        password: "{{CVP_password}}"
    register: token
  - name: API call to get Configlet from CloudVision
    uri:
      method: GET
      validate_certs: no
      return_content: yes
      url: "{{configlet_url}}{{configlet_name}}"
      headers:
        Cookie: "{{token.cookies_string}}"  
    register: configlet_contents
  - name: Debug
    debug:
      msg: "{{configlet_contents}}"
  - name: Write configlet to a file
    copy:
      content: "{{ configlet_contents.content | from_json | json_query('config')}}"
      dest: "configs/Static/ATD-INFRA.cfg"